imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: [survey]
    handlers:
        survey_dumper:
            type:  stream
            channels:  'survey'
            path:  "%kernel.logs_dir%/survey.log"
            level: debug
        mail_catcher:
            type:         fingers_crossed
            action_level: critical
            handler:      mail_spooler
        mail_spooler:
            type:         buffer
            handler:      mailer
        mailer:
            type:         swift_mailer
            from_email:   15x4talks@gmail.com
            to_email:     gleb.sidora@gmail.com
            subject:      Error on 15x4.org

        fs_catcher:
            type:         fingers_crossed
            action_level: error
            handler:      fs_dumper
        fs_dumper:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        console:
            type:  console
