munich_landing:
    path:     /
    host:     "munich.15x4.org"
    defaults: { _controller: "AppBundle:Landing:munich" }

fos_comment_hack:
    path:     /api/threads.html
    defaults: { _controller: "AppBundle:Landing:index" }

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/facebook

vkontakte_login:
    path: /login/vkontakte

twitter_login:
    path: /login/twitter

google_login:
    path: /login/google

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   admin

translation_user_interface:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /admin/translations
