security:
    providers:
        chain_provider:
            chain:
                providers: [in_memory, hwi_oauth]
        in_memory:
            memory:
                users: "%admin_users%"
        hwi_oauth:
            id: hwi_oauth.user.provider

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            logout_on_user_change: true
            pattern: ^/admin
            http_basic:
                provider: in_memory

        main:
            logout_on_user_change: true
            anonymous: ~
            oauth:
                provider: hwi_oauth
                resource_owners:
                    facebook:      /login/facebook
                    vkontakte:     /login/vkontakte
                    twitter:       /login/twitter
                    google:        /login/google
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider
            remember_me:
                secret:   '%secret%'
                lifetime: 2628000 # 1 month in seconds
                path:     /
                always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
