services:
    form.type.sign_up:
        class: AppBundle\Form\SignUpType
        arguments:
            - '@security.token_storage'
            - '@translator'
        tags:
            - { name: form.type }

    form.type.contact_picture:
        class: AdminBundle\Form\ContactPictureType
        calls:
            - ['setKernelRootDir', ['%kernel.root_dir%']]
        tags:
            - { name: form.type }
