services:
    form.type.sign_up:
        class: AppBundle\Form\SignUpType
        arguments:
            - '@security.token_storage'
            - '@translator'
        tags:
            - { name: form.type }
