services:
    15x4.locale_listener:
        class: AppBundle\Subscriber\LocaleSubscriber
        arguments:
          - '@security.token_storage'
          - '@security.authorization_checker'
          - '%kernel.default_locale%'
        tags:
            - { name: kernel.event_subscriber }

    15x4.i18n_updater:
        class: AppBundle\Translations\Updater
        arguments:
          - '@jms_translation.config_factory'
          - '@jms_translation.updater'
          - '%kernel.cache_dir%'

    15x4.i18n.extractor:
        class: AppBundle\Translations\Extractor
        arguments:
          - '@repository.city'
          - '@repository.field'
          - '@repository.tag'
        tags:
            - { name: jms_translation.extractor, alias: 15x4 }

    15x4.featured.aggregator:
        class: AppBundle\FeaturedStats\Aggregator
        arguments:
          - '@repository.lecture'
