services:
    _defaults:
        public: true

    repository.lecture:
        class:                                      AppBundle\Entity\Repository\LectureRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\Lecture ]

    repository.lecturer:
        class:                                      AppBundle\Entity\Repository\LecturerRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\Lecturer ]

    repository.city:
        class:                                      AppBundle\Entity\Repository\CityRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\City ]

    repository.tag:
        class:                                      AppBundle\Entity\Repository\TagRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\Tag ]

    repository.field:
        class:                                      AppBundle\Entity\Repository\FieldRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\Field ]

    repository.event:
        class:                                      AppBundle\Entity\Repository\EventRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\Event ]

    repository.user:
        class:                                      AppBundle\Entity\Repository\UserRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\User ]

    repository.lecture_reaction:
        class:                                      AppBundle\Entity\Repository\LectureReactionRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\LectureReaction ]

    repository.comment_thread:
        class:                                      AppBundle\Entity\Repository\CommentThreadRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\CommentThread ]

    repository.contact:
        class:                                      AppBundle\Entity\Repository\ContactRepository
        factory:                                    ['@doctrine', 'getRepository']
        arguments:                                  [ AppBundle\Entity\Contact ]
